# This file was generated by GoReleaser. DO NOT EDIT.
cask "ankix" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "ca51ad4fbb89d36e1d95c77c93cb4b95b756a158660316602a1665e3f5dc670c"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-darwin-amd64"
      binary "ankix-darwin-amd64", target: "ankix"
    end
    on_arm do
      sha256 "8bbc2569c402f7bf6f1c7c7c82d6eb72b12c1b85a76333b12f0c31bb5e085849"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-darwin-arm64"
      binary "ankix-darwin-arm64", target: "ankix"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e4b7999fcb38079cac8ead436ff175d18b7e9fea6cc1d68e90b14b24827f921"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-linux-amd64"
      binary "ankix-linux-amd64", target: "ankix"
    end
    on_arm do
      sha256 "2d08885ac2544379b5385ceb3e32cbb5ae73f197e56f5c13d3bf42ad5489fad2"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-linux-arm64"
      binary "ankix-linux-arm64", target: "ankix"
    end
  end

  name "ankix"
  desc "Generate contextual Anki translations from Kindle vocab highlights, YouTube transcripts, and web articles"
  homepage "https://github.com/joshgummersall/ankix"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "anki",
    ],
    formula: [
      "ollama",
      "yt-dlp",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
