# This file was generated by GoReleaser. DO NOT EDIT.
cask "ankix" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "c693233b43a490a0dd37d83effb02d78f136237a39441d4da3c51e017eab2758"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-darwin-arm64"
      binary "ankix-darwin-arm64", target: "ankix"
    end
    on_intel do
      sha256 "e07277c4cb8433d245ad4493ebcbfa317000b82af49fe8e857938013357ffde5"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-darwin-amd64"
      binary "ankix-darwin-amd64", target: "ankix"
    end
  end
  on_linux do
    on_arm do
      sha256 "3a03ff588b187a6a2f9e1d5a34a573b4c5eab7dc23fac0e753d5fb3ee64998b0"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-linux-arm64"
      binary "ankix-linux-arm64", target: "ankix"
    end
    on_intel do
      sha256 "49c01e23814380c9bb53891769468e0de39520acf722e61dddb0e589d73b6857"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-linux-amd64"
      binary "ankix-linux-amd64", target: "ankix"
    end
  end

  name "ankix"
  desc "Generate contextual Anki translations from Kindle vocab highlights, YouTube transcripts, and web articles"
  homepage "https://github.com/joshgummersall/ankix"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "anki",
    ],
    formula: [
      "ollama",
      "yt-dlp",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
