# This file was generated by GoReleaser. DO NOT EDIT.
cask "ankix" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "f6f287aa280ab1f89d1b842d00b43b0c0c4ccb65dc8ef1d02c48351630063294"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-darwin-amd64"
      binary "ankix-darwin-amd64", target: "ankix"
    end
    on_arm do
      sha256 "e3dc6b5ae77de9480549c6008bac9179f8e8f332e9ec960151a18b38b5af94b3"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-darwin-arm64"
      binary "ankix-darwin-arm64", target: "ankix"
    end
  end

  on_linux do
    on_intel do
      sha256 "1acf154dbc5859fe225b2df5c981b49ac5e264b088a7e6cf2b760c9a32a667c6"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-linux-amd64"
      binary "ankix-linux-amd64", target: "ankix"
    end
    on_arm do
      sha256 "a14092e1ab7abbd656c610f545a1e0815db4ebb7e3a2470ddada67c84e673be5"
      url "https://github.com/joshgummersall/ankix/releases/download/v#{version}/ankix-linux-arm64"
      binary "ankix-linux-arm64", target: "ankix"
    end
  end

  name "ankix"
  desc "Generate contextual Anki translations from Kindle vocab highlights, YouTube transcripts, and web articles"
  homepage "https://github.com/joshgummersall/ankix"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "anki",
    ],
    formula: [
      "ollama",
      "yt-dlp",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
