# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ankix < Formula
  desc "Generate Anki cards from Kindle vocab highlights and YouTube transcripts"
  homepage "https://github.com/joshgummersall/ankix"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshgummersall/ankix/releases/download/v0.0.0/ankix-darwin-amd64"
      sha256 "e39a18b84a9dd1f688b7e0fca35a734c5535a5d57343e609c381aac25c9ea269"

      define_method(:install) do
        bin.install "ankix-darwin-amd64" => "ankix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joshgummersall/ankix/releases/download/v0.0.0/ankix-darwin-arm64"
      sha256 "71f33a0e17e9b3ad998ca898ae744e4429a91dd63ea631291e55bafb3cf90de0"

      define_method(:install) do
        bin.install "ankix-darwin-arm64" => "ankix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshgummersall/ankix/releases/download/v0.0.0/ankix-linux-amd64"
      sha256 "9d1d8ccb3ccade6fee66da876fbb5082b196c519c9aadec33b5bd83b9fb6e4b6"
      define_method(:install) do
        bin.install "ankix-linux-amd64" => "ankix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshgummersall/ankix/releases/download/v0.0.0/ankix-linux-arm64"
      sha256 "3c646238ab7347244431d3fa635866d07a2514ed1e4bfbd3de1830c4b6b4d686"
      define_method(:install) do
        bin.install "ankix-linux-arm64" => "ankix"
      end
    end
  end

  test do
    system "#{bin}/ankix", "version"
  end
end
